[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "www_Day_Dream"
name = "SFXMixerPatch"
description = "Fixes sound effects to make them respect the SFX volume slider."
websiteUrl = "https://github.com/wwwDayDream/SFXMixerPatch"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "../../README.md"
outdir = "../dist"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/SFXMixerPatch.dll"
target = "/BepInEx/plugins/SFXMixerPatch/"

[publish]
communities = [ "content-warning" ]
[publish.categories]
content-warning = [ "audio" ]
# For a list of valid tags, look at the slug values in https://thunderstore.io/api/experimental/community/game-name/category/
